### ISSUE TITLE
Need explanation of FSSI

### ISSUE THREAD

**Issue by lboening** [GSA/fssi-file-processor#1]
I do not know what the acronym means. Would you be able to explain in the Wiki or the readme?

**Comment by davidlarrimore** [comment]
Ask an you shall receive. Federal Strategic Sourcing Initiative. https://strategicsourcing.gov/ or http://www.gsa.gov/portal/category/25623.

P.S. I have updated both the readme and added a wiki article.

**Comment by lboening** [comment]
Thanks! Saved me time.
